### ISSUE TITLE
[volspotconnect2] Can't switch song using spotify connect

### ISSUE THREAD

**Issue by meggima** [balbuze/volumio-plugins#209]
Since yesterday, the spotify connect 2 plugin on my Volumio shows some strange behaviour:

I can connect from my tablet to my Volumio device and select a song. But once a song started playing, I can't select another song to play. It just starts playing the current song again from the beginning or jumps some seconds back in the current song. I can use the "Next" and "Previous" buttons to move forward and backward in the current playlist/album, but selecting an arbitrary other song doesn't work.

Two other people describe the same problems in this thread in the spotify community: https://community.spotify.com/t5/Other-Partners-Web-Player-etc/Switching-songs-does-not-work-using-spotify-connect/m-p/4685791

I also updated Volumio to version 2.555 and the plugin to version 0.8.3. But the problem still occurs.

My devices (iPad and iPhone) both made an update of the spotify app recently (Spotify version 8.4.93).

**Comment by dumyan** [comment]
I have the same issue. It looks like playing a song doesn't create a new queue, it just starts playing the current one. The only way around this is to add songs to the current queue and use the forward button to play the song/s you've added.

**Comment by yopeople** [comment]
Same issue here.. I also tried raspotify, same problem.

**Comment by aceholgi** [comment]
Same problem here. Did a „factory reset“ and re-installed everything, no success.

**Comment by DBMandrake** [comment]
Same problem here as well although for me I think it started more than a few days ago. To change songs I have to change the source back to my phone, change song then change back to Volumio. I think the issue co-incided with a new version of the iOS spotify client as I noticed the UI has changed significantly.

I'm currently using a build of spotify connect2 from the 16th of November on a test build of Volumio (Cubox-i) and it has been working perfectly since November until this recent Spotify app update.

Hopefully a solution can be found. :+1:

**Comment by balbuze** [comment]
Hello,
Don't waste your time reinstalling the plugin or volumio. Something has been changed from Spotify side. The only solution will be an update of librespot, but no idea when and if it occurs one day. You can still try volspotconnect based on their Cloé library.

**Comment by spinko101** [comment]
same issue here 8-0

**Comment by rubenverboon** [comment]
Same issue here

**Comment by ashthespy** [comment]
There have been some upstream breaking changes from Spotify's side with the new update - a fix is in the pipeline, hopefully by the end of today ;-)

**Comment by jim-miller-gac** [comment]
Same issue here. The only way to change songs is to use the next or previous buttons in the Spotify client. One work around is to stop casting out to Volumio (on R-Pi) and navigate to new songs on the local device (like a computer or laptop). Then, after getting to a pleasant neighborhood of songs, reconnect to Volumio, and use the next or previous buttons to skip songs as needed. Not bad. Looking forward to the fix.

**Comment by aceholgi** [comment]
On librespot the same issue was solved:
https://github.com/librespot-org/librespot/issues/288
Can someone please update volspotconnect2 as well?

**Comment by ashthespy** [comment]
> 
> 
> There have been some upstream breaking changes from Spotify's side with the new update - a fix is in the pipeline, hopefully by the end of today ;-)

Sorry, am on vacation so took longer to push changes - but it should work now. 
To get the changes, you can either manually downloading the binary again from [ashthespy/Vollibrespot](https://github.com/ashthespy/Vollibrespot/releases/tag/v0.1.3) (for your device cpu architecture) or run [getVollibrespot.sh](https://gist.github.com/ashthespy/8f86f1825acbd716fc4b78c63d7ce683).
You could directly pipe it to bash if you like (This is **NOT** recommended for scripts you don't trust!) 
```
curl https://gist.githubusercontent.com/ashthespy/8f86f1825acbd716fc4b78c63d7ce683/raw/06f9a33ff9e39f6a7b83d97ab758cbe98ef64f9e/getVollibrespot.sh | bash
```

**Comment by DBMandrake** [comment]
>To get the changes, you can either manually downloading the binary again from [ashthespy/Vollibrespot](https://github.com/ashthespy/Vollibrespot/releases/tag/v0.1.3) (for your device cpu architecture) or run [getVollibrespot.sh](https://gist.github.com/ashthespy/8f86f1825acbd716fc4b78c63d7ce683).

getVollibrespot.sh didn't work for me. I tried it as an "over the top" install first over the existing plugin but it didn't fix the issue. I then tried uninstalling the old plugin and running it again but it failed to install:

> volumio@volumio:~$ bash getVollibrespot.sh
Failed to stop volspotconnect2.service: Unit volspotconnect2.service not loaded.
Too few arguments.
Detected cpu architecture as armv7l
getVollibrespot.sh: line 41: cd: /data/plugins/music_service/volspotconnect2: No such file or directory
Supported device (arch = armv7l), downloading required packages
https://github.com/ashthespy/Vollibrespot/releases/download/v0.1.3/vollibrespot-armv7l.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   617    0   617    0     0   1037      0 --:--:-- --:--:-- --:--:--  1036
100 4473k  100 4473k    0     0  1975k      0  0:00:02  0:00:02 --:--:-- 4015k
Extracting...
-rw-r--r-- 1 volumio volumio 4581116 Feb 25 07:11 vollibrespot-armv7l.tar.xz
vollibrespot v0.1.3 48346b7 2019-02-25 (librespot 57c9ab5 2019-02-22) -- Built On 2019-02-25
Failed to start volspotconnect2.service: Unit volspotconnect2.service failed to load: No such file or directory.

**Comment by aceholgi** [comment]
For me the install (via ssh as described in the readme) worked. Switching songs worked, but no audio out to the speakers. Going back to 0.74 played audio again.

**Comment by ashthespy** [comment]
@DBMandrake are you sure you are running the latest `volspotconnect2` dev plugin? The below line seems to suggest otherwise.
`Unit volspotconnect2.service failed to load: No such file or directory.`

@aceholgi which version were you on earlier? The script just updates the daemon, not touching the earlier config. Either way, just try reinstalling the latest dev version, it should automatically pick the latest daemon now. You will need to the usual step of entering the plugin settings page and hit save once after to update the output device settings.

**Comment by DBMandrake** [comment]
> are you sure you are running the latest `volspotconnect2` dev plugin? The below line seems to suggest otherwise.
`Unit volspotconnect2.service failed to load: No such file or directory.`

As I mentioned, the first time I tried to install it I did so without removing the original plugin. The installation appeared to work (no error messages and the service was restarted, I didn't capture the output from that attempt) but the problem with it only ever trying to keep playing the same song was not solved.

Only then did I uninstall the existing plugin and try to install this version. (It wasn't made clear that your installer is not a fully installation of the plugin)

**Comment by spinko101** [comment]
Hi, from the Spotify community, someone installed the old version 

see here

https://community.spotify.com/t5/Other-Partners-Web-Player-etc/Switching-songs-does-not-work-using-spotify-connect/m-p/4686716/highlight/true#M62040

https://github.com/balbuze/volumio-plugins/blob/master/plugins/music_service/volspotconnect/readme.md

and it works for me. Maybe a temporary workaround to give the devs more time ;-)

greetings

**Comment by aceholgi** [comment]
@ashthespy No success on my side.... I de-installed the old plugin (0.7.4), installed the dev version (0.8.3) described in the readme, then started getVollibrespot.sh. All installation went fine, songs can be switched (good!) but still no output from my audio hardware (HifiBerry Digi). One thing in the Config screen of the plugin is strange: Initial volume is always at 30%, setting to 100% won't be saved. I'm quite a RasPi dummy, so I can't rule out that it is me who causes problems.....

**Comment by aceholgi** [comment]
The old Plugin (non-2) v. 1.7.6 works for me, too!

**Comment by PabloCasson** [comment]
Great fix thx - this was driving me crazy. Great to have the plugin functioning again

**Comment by balbuze** [comment]
Volspotconnect2 dev version is updated with the fix.
let me know

**Comment by PabloCasson** [comment]
I just uninstalled the existing plugin in web UI and installed the 0.8.4 version using ssh using instructions above. Everything sweet now.

**Comment by balbuze** [comment]
:+1:

**Comment by meggima** [comment]
I installed 0.8.4 version manually via SSH and it resolved the issue for me. @balbuze and @ashthespy  Thank you very much for the fast resolution of the problem. In my opinion, this issue can be closed.

**Comment by balbuze** [comment]
solved

**Comment by DBMandrake** [comment]
> I installed 0.8.4 version manually via SSH and it resolved the issue for me. @balbuze and @ashthespy Thank you very much for the fast resolution of the problem. In my opinion, this issue can be closed.

A fresh install of the updated plugin via SSH has fixed it for me too.

**Comment by jim-miller-gac** [comment]
Thank you.

**Comment by spinko101** [comment]
Thank you very much. Works perfectly :-)  by far the most usefull plug-in for my use... and it frees up my phone as opposed to Aiplay for example... love it !!
